source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'Diagnosis' do

end

target 'DiagnosisTests' do

end

target 'DiagnosisUITests' do

end

pod 'DLRadioButton', '~> 1.4'
pod 'Alamofire', '~> 3.4'
